### ISSUE TITLE
Warning: The `set-output` command is deprecated and will be disabled soon.

### ISSUE THREAD

**Issue by johncblandii** [cloudposse/github-action-docker-build-push#29]
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Bug

> Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

## Expected Behavior

No warning.

## Steps to Reproduce

1. Run the workflow

## Screenshots
If applicable, add screenshots or logs to help explain your problem.

## Environment (please complete the following information):

Anything that will help us triage the bug will help. Here are some ideas:
 - OS: [e.g. Linux, OSX, WSL, etc]
 - Version [e.g. 10.15]

**Comment by goruha** [comment]
@johncblandii it seem solved now
