### ISSUE TITLE
edwardgeorge/jq-action@main generates deprecation warnings 

### ISSUE THREAD

**Issue by hans-d** [cloudposse/github-action-docker-build-push#54]
https://github.com/cloudposse/github-action-docker-build-push/blob/f1139911cacb0c4e6a2a79ae5c215684e87fd8fb/action.yml#L144

The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

The following actions uses node12 which is deprecated and will be forced to run on node16: edwardgeorge/jq-action@main. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/

Seems this action is quite old

**Comment by korenyoni** [comment]
This was resolved with https://github.com/cloudposse/github-action-docker-build-push/pull/59

https://github.com/cloudposse/github-action-jq/blob/c3a312ac606d8588cc9c34597234ddfc7a7129b8/package.json#L21
https://github.com/cloudposse/github-action-jq/blob/c3a312ac606d8588cc9c34597234ddfc7a7129b8/action.yml#L26
